genomes:
  hg19:
    seq: /nfs/glusterfs/ref/genomes/Hsapiens/hg19/seq/hg19.fa
    bwa: /nfs/glusterfs/ref/genomes/Hsapiens/hg19/bwa/hg19.fa
#    chr_lengths: /ngs/reference_data/genomes/Hsapiens/hg19/genome/human.hg19.genome

    dbsnp:       /nfs/glusterfs/ref/genomes/Hsapiens/hg19/variation/dbsnp_138.vcf.gz
    cosmic:      /nfs/glusterfs/ref/genomes/Hsapiens/hg19/variation/CosmicCodingMuts_v68_hg19.vcf.gz
    1000genomes: /nfs/glusterfs/ref/genomes/Hsapiens/hg19/variation/1000G_omni2.5.vcf.gz
    clinvar:     /nfs/glusterfs/ref/genomes/Hsapiens/hg19/variation/clinvar_20140929_hg19.vcf.gz
    oncomine:    /nfs/glusterfs/ref/genomes/Hsapiens/hg19/variation/oncomine.vcf
    dbnsfp:      /nfs/glusterfs/ref/genomes/Hsapiens/hg19/dbNSF/dbNSFP_latest.txt.gz
    # snpeff: /users/klpf990/snpeff/data  # /ngs/reference_data/genomes/Hsapiens/hg19/snpeff/  # data dir path
    snpeff:
      reference: hg19

    exons:    /nfs/glusterfs/ref/genomes/Hsapiens/hg19/bed/Exons/Exons.with_genes.bed
    az_exome: /nfs/glusterfs/ref/genomes/Hsapiens/hg19/bed/Exome-AZ.bed
    refseq:   /nfs/glusterfs/ref/genomes/Hsapiens/hg19/bed/CDS_RefSeq.bed

  GRCh37:
    seq: /nfs/glusterfs/ref/genomes/Hsapiens/GRCh37/seq/GRCh37.fa
    bwa: /nfs/glusterfs/ref/genomes/Hsapiens/GRCh37/bwa/GRCh37.fa

    dbsnp:       /nfs/glusterfs/ref/genomes/Hsapiens/hg19/variation/dbsnp_138.vcf.gz
    cosmic:      /nfs/glusterfs/ref/genomes/Hsapiens/hg19/variation/CosmicCodingMuts_v68_hg19.vcf.gz
    1000genomes: /nfs/glusterfs/ref/genomes/Hsapiens/hg19/variation/1000G_omni2.5.vcf.gz
    clinvar:     /nfs/glusterfs/ref/genomes/Hsapiens/hg19/variation/clinvar_20140929_hg19.vcf.gz
    oncomine:    /nfs/glusterfs/ref/genomes/Hsapiens/hg19/variation/oncomine.vcf
    dbnsfp:      /nfs/glusterfs/ref/genomes/Hsapiens/hg19/dbNSF/dbNSFP_latest.txt.gz
    snpeff:
      reference: GRCh37

    exons:    /nfs/glusterfs/ref/genomes/Hsapiens/GRCh37/bed/Exons/Exons.with_genes.bed
    az_exome: /nfs/glusterfs/ref/genomes/Hsapiens/GRCh37/bed/Exome-AZ.bed
    refseq:   /nfs/glusterfs/ref/genomes/Hsapiens/GRCh37/bed/CDS_RefSeq.bed

queue: all.q
scheduler: sge
resources: [pename=smp]
priority: 0
