genomes:
  hg19-chr21:
    seq:                      ~/googledrive/az/reference_data/genomes/Hsapiens/hg19-chr21/seq/hg19-chr21.fa
    bwa:                      ~/googledrive/az/reference_data/genomes/Hsapiens/hg19-chr21/bwa/hg19-chr21.fa

    dbsnp:                    ~/googledrive/az/reference_data/genomes/Hsapiens/hg19-chr21/variation/dbsnp.vcf.gz
    dbsnp_multi_mafs:         ~/googledrive/az/reference_data/genomes/Hsapiens/hg19-chr21/variation/dbSNP_multi_mafs_latest.txt
    cosmic:                   ~/googledrive/az/reference_data/genomes/Hsapiens/hg19-chr21/variation/cosmic.vcf.gz
    clinvar:                  ~/googledrive/az/reference_data/genomes/Hsapiens/hg19-chr21/variation/clinvar_latest.vcf
    snpeff:
      reference: hg19

    tricky_regions:           ~/googledrive/az/reference_data/genomes/Hsapiens/hg19-chr21/tricky_regions/

  hg19-chr20:
    seq:                      ~/googledrive/az/reference_data/genomes/Hsapiens/hg19-chr20/seq/hg19-chr20.fa
    bwa:                      ~/googledrive/az/reference_data/genomes/Hsapiens/hg19-chr20/bwa/hg19-chr20.fa

    snpeff:
      reference: hg19

    tricky_regions:           ~/googledrive/az/reference_data/genomes/Hsapiens/hg19/tricky_regions/

  hg19:
    seq:                      ~/googledrive/az/reference_data/genomes/Hsapiens/hg19/seq/hg19.fa

    snpeff:
      reference: hg19
    snpeff_transcripts:       ~/googledrive/az/reference_data/genomes/Hsapiens/canonical_transcripts/canonical_transcripts_hg19.txt

    features:                 ~/googledrive/az/reference_data/genomes/Hsapiens/GeneAnnotation/RefSeq/all_features.hg19.canon.bed  # canonical only
    bed_annotation_features:  ~/googledrive/az/reference_data/genomes/Hsapiens/GeneAnnotation/RefSeq/all_features.hg19.canon.bed  # all regions
    cds:                      ~/googledrive/az/reference_data/genomes/Hsapiens/GeneAnnotation/RefSeq/RefSeq_CDS.hg19.bed

    tricky_regions:           ~/googledrive/az/reference_data/genomes/Hsapiens/hg19/tricky_regions/

#    all_transcripts:          ~/googledrive/az/reference_data/genomes/Hsapiens/ref-transcripts_hg19.gtf

  hg38:
    seq:                      ~/googledrive/az/reference_data/genomes/Hsapiens/hg38/seq/hg38.fa

    dbsnp:                    ~/googledrive/az/reference_data/genomes/Hsapiens/hg38/variation/dbsnp.vcf.gz
    cosmic:                   ~/googledrive/az/reference_data/genomes/Hsapiens/hg38/variation/cosmic.vcf.gz
    oncomine:                 ~/googledrive/az/reference_data/genomes/Hsapiens/hg38/variation/oncomine.vcf

    snpeff_transcripts:       ~/googledrive/az/reference_data/genomes/Hsapiens/canonical_transcripts/canonical_transcripts_hg38.txt

    features:                 ~/googledrive/az/reference_data/genomes/Hsapiens/Exons/RefSeq/RefSeq_CDS_miRNA.all_features.hg38.canon.bed  # canonical only
    bed_annotation_features:  ~/googledrive/az/reference_data/genomes/Hsapiens/Exons/RefSeq/RefSeq.all_features.hg38.bed  # all regions
    cds:                      ~/googledrive/az/reference_data/genomes/Hsapiens/Exons/RefSeq/RefSeq_CDS.hg38.bed

    tricky_regions:           ~/googledrive/az/reference_data/genomes/Hsapiens/hg38/tricky_regions/

#    all_transcripts:          ~/googledrive/az/reference_data/genomes/Hsapiens/ref-transcripts_hg19.gtf

queue: ngs.q

smtp_host: 'localhost'

ngs_webserver_preproc_dir: /Users/vlad/Sites/reports


